/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ListingPricingRouteImport } from './routes/listing-pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToolsTagsRouteImport } from './routes/tools/tags'
import { Route as ToolsSubmitRouteImport } from './routes/tools/submit'
import { Route as ToolsSearchRouteImport } from './routes/tools/search'
import { Route as ToolsCategoriesRouteImport } from './routes/tools/categories'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as CheckoutListingSuccessRouteImport } from './routes/checkout/listing-success'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthBannedRouteImport } from './routes/auth/banned'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardSubmissionsIndexRouteImport } from './routes/dashboard/submissions/index'
import { Route as DashboardListingsIndexRouteImport } from './routes/dashboard/listings/index'
import { Route as AdminToolsIndexRouteImport } from './routes/admin/tools/index'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminReviewIndexRouteImport } from './routes/admin/review/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as ToolsTagSlugRouteImport } from './routes/tools/tag.$slug'
import { Route as ToolsSubmitSuccessRouteImport } from './routes/tools/submit.success'
import { Route as ToolsCategorySlugRouteImport } from './routes/tools/category.$slug'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsCreditsRouteImport } from './routes/dashboard/settings/credits'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardSettingsApiKeysRouteImport } from './routes/dashboard/settings/api-keys'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiCronDistributeCreditsRouteImport } from './routes/api/cron/distribute-credits'
import { Route as ApiAvatarUploadRouteImport } from './routes/api/avatar/upload'
import { Route as ApiAvatarSplatRouteImport } from './routes/api/avatar/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminToolsNewRouteImport } from './routes/admin/tools/new'
import { Route as AdminToolsToolIdRouteImport } from './routes/admin/tools/$toolId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingPricingRoute = ListingPricingRouteImport.update({
  id: '/listing-pricing',
  path: '/listing-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsTagsRoute = ToolsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSubmitRoute = ToolsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSearchRoute = ToolsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCategoriesRoute = ToolsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutListingSuccessRoute = CheckoutListingSuccessRouteImport.update({
  id: '/checkout/listing-success',
  path: '/checkout/listing-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBannedRoute = AuthBannedRouteImport.update({
  id: '/auth/banned',
  path: '/auth/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSubmissionsIndexRoute =
  DashboardSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardListingsIndexRoute = DashboardListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminToolsIndexRoute = AdminToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewIndexRoute = AdminReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsTagSlugRoute = ToolsTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSubmitSuccessRoute = ToolsSubmitSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ToolsSubmitRoute,
} as any)
const ToolsCategorySlugRoute = ToolsCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsCreditsRoute =
  DashboardSettingsCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDistributeCreditsRoute =
  ApiCronDistributeCreditsRouteImport.update({
    id: '/api/cron/distribute-credits',
    path: '/api/cron/distribute-credits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAvatarUploadRoute = ApiAvatarUploadRouteImport.update({
  id: '/api/avatar/upload',
  path: '/api/avatar/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarSplatRoute = ApiAvatarSplatRouteImport.update({
  id: '/api/avatar/$',
  path: '/api/avatar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminToolsNewRoute = AdminToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsToolIdRoute = AdminToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listing-pricing': typeof ListingPricingRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/listing-success': typeof CheckoutListingSuccessRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/categories': typeof ToolsCategoriesRoute
  '/tools/search': typeof ToolsSearchRoute
  '/tools/submit': typeof ToolsSubmitRouteWithChildren
  '/tools/tags': typeof ToolsTagsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/tools/$toolId': typeof AdminToolsToolIdRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/api/avatar/upload': typeof ApiAvatarUploadRoute
  '/api/cron/distribute-credits': typeof ApiCronDistributeCreditsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/credits': typeof DashboardSettingsCreditsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/tools/category/$slug': typeof ToolsCategorySlugRoute
  '/tools/submit/success': typeof ToolsSubmitSuccessRoute
  '/tools/tag/$slug': typeof ToolsTagSlugRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/dashboard/submissions/': typeof DashboardSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/listing-pricing': typeof ListingPricingRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/listing-success': typeof CheckoutListingSuccessRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/categories': typeof ToolsCategoriesRoute
  '/tools/search': typeof ToolsSearchRoute
  '/tools/submit': typeof ToolsSubmitRouteWithChildren
  '/tools/tags': typeof ToolsTagsRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/tools/$toolId': typeof AdminToolsToolIdRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/api/avatar/upload': typeof ApiAvatarUploadRoute
  '/api/cron/distribute-credits': typeof ApiCronDistributeCreditsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/credits': typeof DashboardSettingsCreditsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/tools/category/$slug': typeof ToolsCategorySlugRoute
  '/tools/submit/success': typeof ToolsSubmitSuccessRoute
  '/tools/tag/$slug': typeof ToolsTagSlugRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/tools': typeof AdminToolsIndexRoute
  '/dashboard/listings': typeof DashboardListingsIndexRoute
  '/dashboard/submissions': typeof DashboardSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listing-pricing': typeof ListingPricingRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/listing-success': typeof CheckoutListingSuccessRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/categories': typeof ToolsCategoriesRoute
  '/tools/search': typeof ToolsSearchRoute
  '/tools/submit': typeof ToolsSubmitRouteWithChildren
  '/tools/tags': typeof ToolsTagsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/tools/$toolId': typeof AdminToolsToolIdRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/api/avatar/upload': typeof ApiAvatarUploadRoute
  '/api/cron/distribute-credits': typeof ApiCronDistributeCreditsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/credits': typeof DashboardSettingsCreditsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/tools/category/$slug': typeof ToolsCategorySlugRoute
  '/tools/submit/success': typeof ToolsSubmitSuccessRoute
  '/tools/tag/$slug': typeof ToolsTagSlugRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/dashboard/submissions/': typeof DashboardSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/listing-pricing'
    | '/payment'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/checkout/listing-success'
    | '/dashboard/settings'
    | '/tools/$slug'
    | '/tools/categories'
    | '/tools/search'
    | '/tools/submit'
    | '/tools/tags'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/tools/'
    | '/admin/tools/$toolId'
    | '/admin/tools/new'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/avatar/$'
    | '/api/avatar/upload'
    | '/api/cron/distribute-credits'
    | '/api/webhooks/stripe'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/credits'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/tools/category/$slug'
    | '/tools/submit/success'
    | '/tools/tag/$slug'
    | '/admin/categories/'
    | '/admin/review/'
    | '/admin/tags/'
    | '/admin/tools/'
    | '/dashboard/listings/'
    | '/dashboard/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/listing-pricing'
    | '/payment'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/checkout/listing-success'
    | '/dashboard/settings'
    | '/tools/$slug'
    | '/tools/categories'
    | '/tools/search'
    | '/tools/submit'
    | '/tools/tags'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/tools'
    | '/admin/tools/$toolId'
    | '/admin/tools/new'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/avatar/$'
    | '/api/avatar/upload'
    | '/api/cron/distribute-credits'
    | '/api/webhooks/stripe'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/credits'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/tools/category/$slug'
    | '/tools/submit/success'
    | '/tools/tag/$slug'
    | '/admin/categories'
    | '/admin/review'
    | '/admin/tags'
    | '/admin/tools'
    | '/dashboard/listings'
    | '/dashboard/submissions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/listing-pricing'
    | '/payment'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/checkout/listing-success'
    | '/dashboard/settings'
    | '/tools/$slug'
    | '/tools/categories'
    | '/tools/search'
    | '/tools/submit'
    | '/tools/tags'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/tools/'
    | '/admin/tools/$toolId'
    | '/admin/tools/new'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/avatar/$'
    | '/api/avatar/upload'
    | '/api/cron/distribute-credits'
    | '/api/webhooks/stripe'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/credits'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/tools/category/$slug'
    | '/tools/submit/success'
    | '/tools/tag/$slug'
    | '/admin/categories/'
    | '/admin/review/'
    | '/admin/tags/'
    | '/admin/tools/'
    | '/dashboard/listings/'
    | '/dashboard/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListingPricingRoute: typeof ListingPricingRoute
  PaymentRoute: typeof PaymentRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  AuthBannedRoute: typeof AuthBannedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutListingSuccessRoute: typeof CheckoutListingSuccessRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarSplatRoute: typeof ApiAvatarSplatRoute
  ApiAvatarUploadRoute: typeof ApiAvatarUploadRoute
  ApiCronDistributeCreditsRoute: typeof ApiCronDistributeCreditsRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing-pricing': {
      id: '/listing-pricing'
      path: '/listing-pricing'
      fullPath: '/listing-pricing'
      preLoaderRoute: typeof ListingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/tags': {
      id: '/tools/tags'
      path: '/tags'
      fullPath: '/tools/tags'
      preLoaderRoute: typeof ToolsTagsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/submit': {
      id: '/tools/submit'
      path: '/submit'
      fullPath: '/tools/submit'
      preLoaderRoute: typeof ToolsSubmitRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/search': {
      id: '/tools/search'
      path: '/search'
      fullPath: '/tools/search'
      preLoaderRoute: typeof ToolsSearchRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/categories': {
      id: '/tools/categories'
      path: '/categories'
      fullPath: '/tools/categories'
      preLoaderRoute: typeof ToolsCategoriesRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/listing-success': {
      id: '/checkout/listing-success'
      path: '/checkout/listing-success'
      fullPath: '/checkout/listing-success'
      preLoaderRoute: typeof CheckoutListingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/banned': {
      id: '/auth/banned'
      path: '/auth/banned'
      fullPath: '/auth/banned'
      preLoaderRoute: typeof AuthBannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/submissions/': {
      id: '/dashboard/submissions/'
      path: '/submissions'
      fullPath: '/dashboard/submissions/'
      preLoaderRoute: typeof DashboardSubmissionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings/': {
      id: '/dashboard/listings/'
      path: '/listings'
      fullPath: '/dashboard/listings/'
      preLoaderRoute: typeof DashboardListingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/tools/': {
      id: '/admin/tools/'
      path: '/tools'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AdminToolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review/': {
      id: '/admin/review/'
      path: '/review'
      fullPath: '/admin/review/'
      preLoaderRoute: typeof AdminReviewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/tag/$slug': {
      id: '/tools/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tools/tag/$slug'
      preLoaderRoute: typeof ToolsTagSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/submit/success': {
      id: '/tools/submit/success'
      path: '/success'
      fullPath: '/tools/submit/success'
      preLoaderRoute: typeof ToolsSubmitSuccessRouteImport
      parentRoute: typeof ToolsSubmitRoute
    }
    '/tools/category/$slug': {
      id: '/tools/category/$slug'
      path: '/category/$slug'
      fullPath: '/tools/category/$slug'
      preLoaderRoute: typeof ToolsCategorySlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/credits': {
      id: '/dashboard/settings/credits'
      path: '/credits'
      fullPath: '/dashboard/settings/credits'
      preLoaderRoute: typeof DashboardSettingsCreditsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/api-keys': {
      id: '/dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/distribute-credits': {
      id: '/api/cron/distribute-credits'
      path: '/api/cron/distribute-credits'
      fullPath: '/api/cron/distribute-credits'
      preLoaderRoute: typeof ApiCronDistributeCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/upload': {
      id: '/api/avatar/upload'
      path: '/api/avatar/upload'
      fullPath: '/api/avatar/upload'
      preLoaderRoute: typeof ApiAvatarUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$': {
      id: '/api/avatar/$'
      path: '/api/avatar/$'
      fullPath: '/api/avatar/$'
      preLoaderRoute: typeof ApiAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/tools/new': {
      id: '/admin/tools/new'
      path: '/tools/new'
      fullPath: '/admin/tools/new'
      preLoaderRoute: typeof AdminToolsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools/$toolId': {
      id: '/admin/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/admin/tools/$toolId'
      preLoaderRoute: typeof AdminToolsToolIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminToolsToolIdRoute: typeof AdminToolsToolIdRoute
  AdminToolsNewRoute: typeof AdminToolsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminReviewIndexRoute: typeof AdminReviewIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
  AdminToolsIndexRoute: typeof AdminToolsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminToolsToolIdRoute: AdminToolsToolIdRoute,
  AdminToolsNewRoute: AdminToolsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminReviewIndexRoute: AdminReviewIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
  AdminToolsIndexRoute: AdminToolsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsCreditsRoute: typeof DashboardSettingsCreditsRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsCreditsRoute: DashboardSettingsCreditsRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardListingsIndexRoute: typeof DashboardListingsIndexRoute
  DashboardSubmissionsIndexRoute: typeof DashboardSubmissionsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardListingsIndexRoute: DashboardListingsIndexRoute,
  DashboardSubmissionsIndexRoute: DashboardSubmissionsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ToolsSubmitRouteChildren {
  ToolsSubmitSuccessRoute: typeof ToolsSubmitSuccessRoute
}

const ToolsSubmitRouteChildren: ToolsSubmitRouteChildren = {
  ToolsSubmitSuccessRoute: ToolsSubmitSuccessRoute,
}

const ToolsSubmitRouteWithChildren = ToolsSubmitRoute._addFileChildren(
  ToolsSubmitRouteChildren,
)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsCategoriesRoute: typeof ToolsCategoriesRoute
  ToolsSearchRoute: typeof ToolsSearchRoute
  ToolsSubmitRoute: typeof ToolsSubmitRouteWithChildren
  ToolsTagsRoute: typeof ToolsTagsRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ToolsCategorySlugRoute: typeof ToolsCategorySlugRoute
  ToolsTagSlugRoute: typeof ToolsTagSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsCategoriesRoute: ToolsCategoriesRoute,
  ToolsSearchRoute: ToolsSearchRoute,
  ToolsSubmitRoute: ToolsSubmitRouteWithChildren,
  ToolsTagsRoute: ToolsTagsRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ToolsCategorySlugRoute: ToolsCategorySlugRoute,
  ToolsTagSlugRoute: ToolsTagSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListingPricingRoute: ListingPricingRoute,
  PaymentRoute: PaymentRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  AuthBannedRoute: AuthBannedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutListingSuccessRoute: CheckoutListingSuccessRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarSplatRoute: ApiAvatarSplatRoute,
  ApiAvatarUploadRoute: ApiAvatarUploadRoute,
  ApiCronDistributeCreditsRoute: ApiCronDistributeCreditsRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
